services:
  cache_context.timezone:
    class: Drupal\adminconfigform\CacheContext\TimezoneCacheContext
    arguments: ['@adminconfigform.timezone_service']
    tags:
      - { name: cache_context }
  adminconfigform.timezone_service:
    class: Drupal\adminconfigform\TimeZoneServices